/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domen.Rezervacija;
import domen.Status;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import kontroler.Komunikacija;

/**
 *
 * @author LENOVO
 */
public class DijalogPretraziRecenzije extends javax.swing.JDialog {

    /**
     * Creates new form DijalogPretraziRecenzije
     */
    Rezervacija r;
    SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
    public DijalogPretraziRecenzije(java.awt.Frame parent, boolean modal,Rezervacija r) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.r=r;
        popuniCbStatus();
        txtGost.setText(r.getGost().toString());
        txtGost.setEnabled(false);
        txtApartman.setText(r.getApartman().toString());
        txtApartman.setEnabled(false);
        
        cbStatus1.setSelectedItem(r.getStatus());
          if(cbStatus1.getSelectedItem()==Status.POTVRDJENA){
            cbStatus1.setEnabled(false);
        }
        txtDatumOd1.setText(sdf.format(r.getDatumOd()));
        txtDatumDo1.setText(sdf.format(r.getDatumDo()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbStatus1 = new javax.swing.JComboBox<>();
        txtDatumDo1 = new javax.swing.JTextField();
        txtDatumOd1 = new javax.swing.JTextField();
        btnIzmeniRezervaciju = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtGost = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApartman = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Izmeni rezervaciju"));

        jLabel6.setText("Datum od:");

        jLabel8.setText("Datum do:");

        jLabel7.setText("Status:");

        btnIzmeniRezervaciju.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIzmeniRezervaciju.setText("<html>IZMENI<br>REZERVACIJU</html>");
        btnIzmeniRezervaciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniRezervacijuActionPerformed(evt);
            }
        });

        jLabel1.setText("Gost:");

        jLabel2.setText("Apartman:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIzmeniRezervaciju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDatumOd1)
                        .addComponent(txtDatumDo1)
                        .addComponent(cbStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtGost, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addComponent(txtApartman)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(cbStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDatumOd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtDatumDo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApartman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addComponent(btnIzmeniRezervaciju, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniRezervacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniRezervacijuActionPerformed
        // TODO add your handling code here:
       
      
          try {
              
               Date datumOd = sdf.parse(txtDatumOd1.getText());
              Date datumDo = sdf.parse(txtDatumDo1.getText());
              r.setDatumOd(datumOd);
              r.setDatumDo(datumDo);
              
              long diffInMillis = datumDo.getTime() - datumOd.getTime();
            int brojDana =(int)TimeUnit.DAYS.convert(diffInMillis, TimeUnit.MILLISECONDS);

            int ukupnaCena = brojDana*r.getApartman().getCena();
              r.setUkupnaCena(ukupnaCena);
               if(cbStatus1.isEnabled()==true){
              Status status = (Status) cbStatus1.getSelectedItem();
              r.setStatus(status);
              }
               Komunikacija.getInstance().zapamtiRezervaciju(r);
              JOptionPane.showMessageDialog(this, "Sistem je izmenio rezervaciju");
               
          } catch (ParseException ex) {
              Logger.getLogger(DijalogPretraziRecenzije.class.getName()).log(Level.SEVERE, null, ex);
          } catch (Exception ex) {
              JOptionPane.showMessageDialog(this, "Sistem ne moze da izmeni rezervaciju");
            Logger.getLogger(DijalogPretraziRecenzije.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        
        
        this.dispose();
    }//GEN-LAST:event_btnIzmeniRezervacijuActionPerformed

    public JComboBox<Status> getCbStatus1() {
        return cbStatus1;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniRezervaciju;
    private javax.swing.JComboBox<Status> cbStatus1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApartman;
    private javax.swing.JTextField txtDatumDo1;
    private javax.swing.JTextField txtDatumOd1;
    private javax.swing.JTextField txtGost;
    // End of variables declaration//GEN-END:variables

    
    
    
    private void popuniCbStatus() {

         getCbStatus1().removeAllItems();
        for(Status s: Status.values()){
            getCbStatus1().addItem(s);
        }
        

    }

  
}
