/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Apartman;
import domen.Gost;
import domen.Recenzija;
import domen.Rezervacija;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.Komunikacija;
import modeli.ModelTabeleRecenzije;
import modeli.ModelTabeleRezervacije;
import modeli.*;
/**
 *
 * @author LENOVO
 */
public class FormaRecenzija extends javax.swing.JFrame {

    /**
     * Creates new form FormaRecenzija
     */
    Gost ulogovaniGost;
    ModelTabeleRecenzije modelRecenzije;
ModelTabeleRecenzijeSvi modeliRecenzijeSvi;
    public FormaRecenzija(Gost ulogovaniGost) {
        initComponents();
        setLocationRelativeTo(null);
        this.ulogovaniGost = ulogovaniGost;

        popuniTabeluRecenzija();
        popuniTabeluRecenzijaZaUlogovanog();
    }

    public void popuniTabeluRecenzija() {
        try {
            this.modeliRecenzijeSvi = new ModelTabeleRecenzijeSvi(
                    Komunikacija.getInstance().ucitajListuRecenzija()
            );

            tblSveRecenzije1.setModel(this.modeliRecenzijeSvi);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita sve rezervacije");
            Logger.getLogger(IzmeniGosta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void popuniTabeluRecenzijaZaUlogovanog() {
        try {
            ArrayList<Recenzija> lista = Komunikacija.getInstance().ucitajListuRecenzija();
             ArrayList<Recenzija>listaDatogGosta = new ArrayList<>();
            for(Recenzija recenzija:lista){
                if(recenzija.getRezervacija().getGost().getGostID()==ulogovaniGost.getGostID()){
                    listaDatogGosta.add(recenzija);
                }
            }
            
              this.modelRecenzije = new ModelTabeleRecenzije(listaDatogGosta);
              
            tblGostRec.setModel(this.modelRecenzije);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita sve rezervacije");
            Logger.getLogger(IzmeniGosta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblGostRec = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtPretraziRec = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSveRecenzije1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblGostRec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblGostRec);

        jLabel1.setText("Pretrazi svoje recenzije:");

        txtPretraziRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPretraziRecActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("DODAJ SVOJU RECENZIJU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblSveRecenzije1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblSveRecenzije1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtPretraziRec)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 206, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(440, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(9, 9, 9)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPretraziRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(144, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new DijalogRecenzija(this, rootPaneCheckingEnabled, this.ulogovaniGost).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPretraziRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPretraziRecActionPerformed
        // TODO add your handling code here:
        Recenzija param = new Recenzija();
String pretraga = txtPretraziRec.getText().trim(); 
param.setKomentar(txtPretraziRec.getText().trim()); 

//try {
//    int ocena = Integer.parseInt(pretraga);
//    param.setOcena(ocena);
//} catch (NumberFormatException e) {
//    
//}

        try {
            ArrayList<Recenzija> lista = Komunikacija.getInstance().retraziRecenzije(param);
             ArrayList<Recenzija>listaDatogGosta = new ArrayList<>();
            for(Recenzija recenzija:lista){
                if(recenzija.getRezervacija().getGost().getGostID()==ulogovaniGost.getGostID()){
                    listaDatogGosta.add(recenzija);
                }
            }
            
            
          this.modelRecenzije = new ModelTabeleRecenzije(listaDatogGosta);
              tblGostRec.setModel(modelRecenzije);
         

            if(this.modelRecenzije.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje recenzije po zadatoj vrednosti");
            } else {

                JOptionPane.showMessageDialog(this, "Sistem je nasao recenzije po zadatoj vrednosti");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje recenzije po zadatoj vrednosti");
            Logger.getLogger(IzmeniGosta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtPretraziRecActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblGostRec;
    private javax.swing.JTable tblSveRecenzije1;
    private javax.swing.JTextField txtPretraziRec;
    // End of variables declaration//GEN-END:variables

   
}
